# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:53
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('category_parent', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emailverify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=50)),
                ('registration_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_status', models.BooleanField(default=True)),
                ('subscription_type', models.CharField(choices=[('Yearly', 'Yearly'), ('Trial', 'Trial')], default='Trial', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('Percentage', 'Percentage Based Discount'), ('Dollar', 'Dollar Value Discount'), ('Shipping', 'Free Shipping'), ('Gift', 'Free Gift')], default='NULL', max_length=100)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valid_till', models.IntegerField(default=0)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product_color_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(default='NULL', max_length=50)),
                ('images', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Product_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Offers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('uploaded_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=0)),
                ('product_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('deliver_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('return_allowed', models.BooleanField(default=True)),
                ('return_within', models.IntegerField(default=0)),
                ('product_speficication', models.TextField(default=0)),
                ('material_speficication', models.TextField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product_offer',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.AddField(
            model_name='product_color_images',
            name='product_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='product_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Categories'),
        ),
        migrations.AddField(
            model_name='merchant_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
    ]
