# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='return_within',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
