# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_auto_20170322_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailverify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashkey', models.CharField(max_length=50)),
                ('Reg_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
