# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_emailverify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverify',
            old_name='hashkey',
            new_name='activation_key',
        ),
    ]
