# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170329_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverify',
            old_name='Reg_time',
            new_name='registration_time',
        ),
    ]
