# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170329_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('category_parent', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('Percentage', 'Percentage Based Discount'), ('Dollar', 'Dollar Value Discount'), ('Shipping', 'Free Shipping'), ('Gift', 'Free Gift')], default='NULL', max_length=100)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valid_till', models.IntegerField(default=0)),
                ('discount_amt', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product_color_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('Red', 'Red'), ('Pink', 'Pink'), ('Black', 'Black'), ('White', 'White')], default='NULL', max_length=50)),
                ('images', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('uploaded_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_cost', models.FloatField(default=0)),
                ('deliver_charges', models.FloatField(default=0)),
                ('return_allowed', models.BooleanField(default=True)),
                ('return_within', models.IntegerField(default=0)),
                ('product_speficication', models.TextField(default=0)),
                ('material_speficication', models.TextField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product_color_images',
            name='product_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='product_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Categories'),
        ),
        migrations.AddField(
            model_name='offers',
            name='product_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
    ]
