# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20170330_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount_amt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='deliver_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
