# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20170330_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Merchants')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products')),
            ],
        ),
    ]
