# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_merchant_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_products',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
